apiVersion: v2
name: packmind
type: application
version: 1.4.0
appVersion: 1.3.1
description: Elevate developers and code with Packmind
home: https://github.com/packmindhub/packmind-helm-chart
maintainers:
  - name: cteyton
    email: cedric.teyton@packmind.com
    url: https://github.com/cteyton
icon: https://packmind.com/wp-content/uploads/2024/01/LogoMark_Packmind.png
