app:
  images:
    api: packmind/packmind-api
    proxy: packmind/packmind-proxy
    detection: packmind/packmind-detection
    aiagent: packmind/packmind-ai-agent
    tag: 1.2.3  # comment this if the images below are custom and contain already a tag
    imagePullPolicy: Always
    # secret:
      # name: docker-registry-key
      # dockerconfigjson:
  annotations: {}  # annotations to add on Packmind deployments
  labels: {}  # annotations to add on Packmind deployments
  front:
    replicas: 1
  detection:
    replicas: 2
    # autoscaling:
    #   enabled: true
    #   minReplicas: 1
    #   maxReplicas: 4
    #   targetCPUUtilizationPercentage: 50
  aiagent:
    replicas: 2
    #  autoscaling:
    #    enabled: true
    #    minReplicas: 1
    #    maxReplicas: 20
    #    targetCPUUtilizationPercentage: 50
    variables:
      # LOG_LEVEL: debug
      # MAX_DEBUG_RETRY: 10
      # MAX_JOBS_TIMEOUT: 600000
      # AI_REQUEST_TIMEOUT: 60000
  databaseEmbedded:
    enabled: true  # use an internal mongodb in the cluster
    mongodbImage: mongo:6.0.23
    pvc:
      enabled: true
      storageClassName: local-path
      storage: 1Gi
      accessModes: ReadWriteOnce
  databaseUri:
    value: "mongodb://mongodb:27017/packmind"
    # secret:
    #   name: mongodb-secret
    #   key: mongodb-uri
  variables: {}   # Initialize as empty map
    # PACKMIND_URL: http://my.packmind.com
  secrets:  # env variables injected from secrets
  # - envVariable: THEMIS_AUTH_CONFIG_ADMIN_PASSWORD
  #   secretName: secret-openldap
  #   secretKey: openldap-password
  redis:
    pvc:
      enabled: false
  resources:
    api:
      limits:
        cpu: "1000m"
        memory: "2Gi"
      requests:
        cpu: "200m"
        memory: "128Mi"
    detection:
      limits:
        cpu: "1000m"
        memory: "2Gi"
      requests:
        cpu: "500m"
        memory: "256Mi"
    aiagent:
      limits:
        cpu: "1000m"
        memory: "2Gi"
      requests:
        cpu: "500m"
        memory: "256Mi"
    front:
      limits:
        cpu: "500m"
        memory: "512Mi"
      requests:
        cpu: "100m"
        memory: "128Mi"
    mongodb:
      limits:
        cpu: "500m"
        memory: "512Mi"
      requests:
        cpu: "100m"
        memory: "128Mi"

affinity: {}
nodeSelector: {}
tolerations: []

services:
  annotations: {}  # annotations to add on Packmind services
  labels: {}  # annotations to add on Packmind services

ingress:
  enabled: true
  className: ""
  annotations: {}
  labels: {}
  tls:
    enabled: false
    # secrets:
    #   app: app-tls-secret
  hostnames:
    app: my.packmind.local
